# Generated by Django 5.1.7 on 2025-03-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
