# Generated by Django 5.1.7 on 2025-03-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
