# Generated by Django 5.1.7 on 2025-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_teacher_subject_alter_teacher_id_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
