# Generated by Django 5.1.7 on 2025-03-14 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_teacher_groups_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.teacher')),
            ],
        ),
    ]
